baseURL = "https://nos4fe.site/"
languageCode = "zh-Hans"
DefaultContentLanguage = "zh"
title = "Ch4rc0al 的博客"
theme = "dream"
enableRobotsTXT = true
hasCJKLanguage = true


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Ch4rc0al"
  description = "Ch4rc0al 的学习笔记与生活随笔"
  avatar = "/me/avatar.jpg"
  motto = "Being a hASKER"
  categoriesLimitInHeader = 6
  # headerBottomText = ""
  
  enableSearch = true
  
  rss = true
  
  email = "charc0al@vip.qq.com"
  
  favicon = "/favicon.ico"
  
  highlightjs = true
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "tomorrow-light"
  highlightjsThemeDark = "tomorrow-dark"
  
  darkNav = true
  dark404 = true