baseURL = "https://nos4fe.site/"
languageCode = "zh-Hans"
DefaultContentLanguage = "zh"
title = "Ch4rc0al 的博客"
theme = "dream"
enableRobotsTXT = true
hasCJKLanguage = true


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Ch4rc0al"
  description = "Ch4rc0al 的学习笔记与生活随笔"
  avatar = "/me/avatar.jpg"
  motto = "I will try anything at once."
  categoriesLimitInHeader = 6
  # headerBottomText = ""
  
  enableSearch = true
  
  rss = true
  valine = true
  LEANCLOUD_APP_ID = "RnBK7pdlGCP1z9aUvG0i12dT-gzGzoHsz"
  LEANCLOUD_APP_KEY = "HHifu4neoiaqUpBmQN5RCAAm"
  
  email = "charc0al@vip.qq.com"
  
  favicon = "/favicon.ico"
  
  highlightjs = true
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"
  
  darkNav = true
  dark404 = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]